### ISSUE TITLE
What is $objectManager and where does it come from

### ISSUE THREAD

**Issue by manju16832003** [nelmio/alice#307]
From the below documentation what is $objectManager and where does it come from. 
https://github.com/nelmio/alice#table-of-contents
$objects = \Nelmio\Alice\Fixtures::load(__DIR__.'/fixtures.yml', $objectManager);

**Comment by knugen** [comment]
It is an instance of either `Nelmio\Alice\PersisterInterface` or `Doctrine\Common\Persistence\ObjectManager`.

Basically, Alice needs a way to talk to your database. If you are using [Doctrine ](https://github.com/doctrine/doctrine2) you can pass in the standard EntityManager instance, otherwise you will have to provide your own implementation of the above interface.

**Comment by theofidry** [comment]
perfect answer from @knugen, do you still have an issue with it @manju16832003?

**Comment by manju16832003** [comment]
Thank you @knugen .
@theofidry  No, Now its clear :-). 
Thank you guys for the help.
