### ISSUE TITLE
Include range array

### ISSUE THREAD

**Issue by loostro** [nelmio/alice#491]
Hi,

I have a situation where I would like to do:

```yaml
Acme\DemoBundle\Role:
    role{User, Admin, SuperAdmin}:
        name: '<current()>'
```

However my list `User, Admin, SuperAdmin` is super long, about 100 entries.

Is it possible to use a provider function to provide range arguments?

Something like:

```php
# RolesProvider.php
class RolesProvider
{
    public function rolesList()
    {
        return ['User', 'Admin', 'SuperAdmin']
    }
}
```

```yaml
# roles.yml
Acme\DemoBundle\Role:
    role{<rolesList()>}:
        name: '<current()>'
```

**Comment by theofidry** [comment]
I'm not really fond of the idea to be honest. If `rolesList()` was dynamic, this would cause problems in v3 because you have two steps: generating the list of fixtures and generating the objects described by fixtures. The result of the first step should be static to be cacheable, with your approach this would no longer be true without talking of the complexity it may bring.

An easy alternative for your example would be:

```
# roles.yml
Acme\DemoBundle\Role:
    role{0..2}:
        name: '<rolesList(<current()>)>'
```

assuming nested function works (it does not very well in v2), so another alternative would be:

```
# roles.yml
Acme\DemoBundle\Role:
    role{0..2}:
        name (unique): '<rolesList()>'
```

**Comment by loostro** [comment]
I don't need `rolesList` to be dynamic. Thanks for the alternative you posted. I think it will do for my purposes.
