### ISSUE TITLE
How do you handle entities that hold 2 references to another entity?

### ISSUE THREAD

**Issue by appeltaert** [nelmio/alice#578]
To use my scenario as an example:

`Company` has many `Medium`, `Medium` is the owning side, so `Medium` is created with a reference to `Company`, so far so good.

Now `Company` also has a relation to a `Medium` entity for it's logo.. As far as i can tell this isn't possible without dropping the constraint `Medium -> Company` and then something like:

```php
function setLogo(Medium $logo) {
    $this->logo = $logo;
    $logo->setCompany($this);
}
```

Haven't even tested if these changes are flushed by alice since this would also require me to drop the `Company` constraint on `Medium`.. Not really an option.

I guess a custom data provider could work that creates them in order, but that's not an option either since I need both references further on..

Any suggestions?

**Comment by appeltaert** [comment]
If it's not possible and a welcome addition, i can work on that.

**Comment by theofidry** [comment]
@appeltaert just to make sure I understood the problem correctly: you have two types of relations between `Company` and `Medium`, but you can set properly both because of the "accessor limitation", i.e. if you have `setMedium` and `addMedium` each one for a different relation, alice will pick only one. Is that correct?

Assuming the above is correct, in alice 2.x, I would flat out say it's very hard, most likely if you can do it in a processor, that's cool, otherwise I'm not sure where you can do it. Processors have hooks for pre and post persist + flush.

In Alice 3.x I think you can have more flexibility regarding this issue. It's planned to support calling arbitrary methods: https://github.com/nelmio/alice/issues/388 (end of the issue description). Planned but not added yet. Also note that in Alice 3.x things change quite a lot (for the better), and the persistence is done in https://github.com/theofidry/AliceDataFixtures instead. HautelookAliceBundle 2.0 beta has been out using both alice 3.x and AliceDataFixtures if you want to give it a try.

**Comment by appeltaert** [comment]
@theofidry should've included some yml :)

It's very simple:

```yml
Company:
    acme:
        logo: '@logo'

Medium:
    acme_medium:
        company: '@acme'
```

`Medium` needs a `Company` reference, it owns the relation. But `Company` has a reference to `Medium` for its logo. So the logo needs to be persisted first for its m2o relation to `Company`, but then there's also a o2o relation from `Company` to `Medium` for its logo.

Can i cover this with the 2.0 beta of the bundle?

**Comment by theofidry** [comment]
```yaml
Company:
    acme:
        media: [ '@logo', '@medium*' ]
        logo: '@logo'

Medium:
    logo:
        company: '@acme'
```

Should do the trick. 

>So the logo needs to be persisted first for its m2o relation to Company..

AFAIK Doctrine ORM handles such cases. I think you can cover this case with both HautelookAliceBundle 1.x and 2.x.

**Comment by appeltaert** [comment]
I guess i could fix it indeed with an additional setter on `Medium` using the 'after population step' from 3.0:

```yml
Medium:
    logo:
        __calls:
            - setAsLogoForCompany: [@acme]
```

```php
function setAsLogoForCompany(Company $c) {
    $c->setLogo($this);
}
```

Would this flush() the changes in the company reference though?

Don't like it though since it needs a public setter just for fixtures loading. Is it possible to call a service or something in the 'after population step'?

**Comment by theofidry** [comment]
>I guess i could fix it indeed with an additional setter

I can't say I don't have your PHP classes :P How would you do it in plain PHP? Also note that if you don't like the idea to add an accessor just for it, you can use the constructor instead (and make use of the `__construct` notation).

>Would this flush() the changes in the company reference though?

This extra step is done before any persistence, so yeah.

> Is it possible to call a service or something in the 'after population step'?

That's the "configurator" section of the #388, nothing decided yet at this point.

If you still have doubts, given me:

- you PHP classes
- the fixtures
- how you would do it in plain PHP

**Comment by appeltaert** [comment]
Oh man, github needs some sort of real-time awareness of people writing comments :) Anyway, thanks for wasting your time. I'll try to make it up soon contributing on some of the bugs or something

**Comment by theofidry** [comment]
No worries, any help is welcomed I need feedback for the beta releases ;)
