### ISSUE TITLE
 Argument 3 passed to [...] must be of the type array, string given, called in [...] on line   275 and defined.

### ISSUE THREAD

**Issue by volneivolff** [nelmio/alice#580]
[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 3 passed to Nelmio\Alice\Fixtures\Builder\Builde
  r::build() must be of the type array, string given, called in C:\CURSOS\symfony\
  symfony_course\vendor\nelmio\alice\src\Nelmio\Alice\Fixtures\Loader.php on line
  275 and defined

**Comment by theofidry** [comment]
Hey @volneivolff.

I must say I'm not really sure on how to take your issue. There *is* tests for most scenario, if you are encountering such an issue it's not because the library is outright broken (otherwise you would not have 3K+ of daily downloads). So unless you  are willing to provide a bit more context on how you encountered this, I cannot help you.

**Comment by poteirard** [comment]
For those facing the same problem check the structure of the yml :) 
I was missing the name of the fixture >.<

**Comment by xspokex** [comment]
@poteirard Good catch. I had a missing space after the ':' as in:
`name(unique):<lastName()>`
instead of
`name(unique): <lastName()>`

I didn't think that yml is so sensitive.
