### ISSUE TITLE
[Question] How to generate arbitrary number of records?

### ISSUE THREAD

**Issue by bwegrzyn** [nelmio/alice#621]
Is it possible to specify the number of records we want to generate at run time?

For example, I have a CLI command where the user can generate a bunch of test data for my application. This command allows them to specify how many users/groups/organizations/etc they want to generate.

What would be the best way to do this? Obviously, hard coding the ranges via `user_{1...10}` won't  work here, and I'd like to avoid running the generation command multiple times.

Any tips?

**Comment by theofidry** [comment]
Hm, it's a bit of an edge case, but I think the easiest way would be to load a PHP array rather than a YAML file, to make the `'user_{1..10}` string dynamic. This should work on both 2.x and 3.x.

I'm not really in favour of adding natively an easier way to do that, as it would surely be done by allowing the usage of parameters in the fixture IDs. Besides being a pain to handle, it's quite dangerous as well: alice is not designed to generate dozen of thousands of objects (even if 3.x should perform better here) and much less the Doctrine if you are using it in 2.x.

**Comment by bwegrzyn** [comment]
@theofidry Thanks for the answer!

Is the `user_{1..10}` syntax supported in PHP array fixtures, or should I generate the full array myself?

**Comment by theofidry** [comment]
Yes, the YAML format is parsed as a regular PHP array. Everything you use
in YAML works in PHP :)

**Comment by bwegrzyn** [comment]
Perfect, thanks! I've got it working using a PHP array.

**Comment by theofidry** [comment]
😄
