### ISSUE TITLE
__calls and __factory methods receive uninitialized objects

### ISSUE THREAD

**Issue by norbert-yoimo** [nelmio/alice#752]
If you have a fixture that has `__calls`, and/or `__factory`, and these methods accept an entity reference through alice, that referenced entity will be uninitialized. Example:

```yml
POC\Entity\Address:
    address:
        country: <country()>
        city: <city()>

POC\Entity\Person:
    person:
        __factory: { createWithAddress: [ "@address" ] }
```

```php
<?php

namespace POC\Entity;

class Person {
    private $city;
    private $country;

    public static function createWithAddress($address) {
        $instance = new self();
        $instance->city = $address->getCity();
        $instance->country = $address->getCountry();
        return $instance;
    }

}
```
The `Person` entity produced by alice will have `NULL`s on `$city`, and `$country`. If you place a `var_dump($address)` inside the `createWithAddress` method, you will see that every property of `$address` is NULL:

```php
$loader = new NativeLoader();
$objects = $loader->loadFile(__DIR__ .'/fixture.yml');

var_dump($objects);
```
```
class Nelmio\Alice\ObjectSet#246 (2) {
  private $parameters =>
  array(0) {
  }
  private $objects =>
  array(2) {
    'address' =>
    class POC\Entity\Address#234 (3) {
      private $id =>
      NULL
      private $country =>
      string(36) "United States Minor Outlying Islands"
      private $city =>
      string(15) "Port Betsyhaven"
    }
    'person' =>
    class POC\Entity\Person#244 (2) {
      private $city =>
      NULL
      private $country =>
      NULL
    }
  }
}
```

I believe this might be because the methods in __calls, and __factory are called too early, before the properties are initialized on the entities.

I have created a POC repository that you can clone, hope it helps:

https://github.com/norbert-yoimo/alice-poc

**Comment by theofidry** [comment]
Thanks for the detailed bug reported, that eased a lot the debug :)

In the end, it's not *really* a bug, if you consider the following:

```yaml
stdClass:
    dummy:
        relatedDummy: '@dummy*'
```

This is a valid case and obviously you cannot assume the references returned will be complete as otherwise you would have a circular dependency.

However I agree that giving complete objects whenever possible should be done. I though that was the case but your issued proved me wrong, so now it's done 😄 

Note however that Alice will **attempt** to return a complete object, if failing to do so an incomplete object will be returned.
