### ISSUE TITLE
Deprecation notices when using gedmo nested tree

### ISSUE THREAD

**Issue by danut007ro** [nelmio/alice#779]
Hello,

It's my first time using Alice, so bear with me. I'm loading some fixtures that are using nested tree from gedmo doctrine extensions. I get deprecation notices that were introduced in https://github.com/nelmio/alice/pull/607
Since I don't want to expose **lft**, **rgt**, **lvl** properties from entity as public or with setters, how can I get rid of the deprecation notices?

Thank you.

**Comment by theofidry** [comment]
Hi,

They are deprecated because you can't access them (private/protected properties) out of the box anymore. You will either have to change the accessor (cf. [this link](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#custom-accessor)) for another one or declare your own.

TL:DR; it's ok, it just means you'll have to change things a little if you upgrade

**Comment by danut007ro** [comment]
Thanks, that's clear enough.
