### ISSUE TITLE
Could not determine how to assign a (DC2Type:simple_array) longtext type

### ISSUE THREAD

**Issue by visiover** [nelmio/alice#802]
I'm using Alice 2.x with Doctrine fixtures and mySql.
I'm getting this error when I'm trying to load some fixtures: 

  ```
Could not determine how to assign roles to a MyVendor\MyClass object
Type: UnexpectedValueException
  File: Packages/Libraries/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Populator.php
  Line: 104
```
My Yaml file looks like something like this : 

MyVendor\MyClass:
   MyObject:
     objectName: "myName"
     roles: "User:free"

roles is of type longtext (DC2Type:simple_array), It seems that Alice can't handle that type, Should i write my own populator or what should i do here?

**Comment by theofidry** [comment]
It's more likely to be a PHP issue rather than the doctrine type itself. Check if you have the necessary accessors eventually debugging it to see what it tries to get. I don't really remember what's the behaviour there in 2.x tbh. Writing your own populator could be doable but a real PITA due to 2.x design, so avoid that as much as possible. Last resort IIRC the was a `__config` or `__setter` option to make use of a configurator.

**Comment by visiover** [comment]
Thank you very much for you quick answer :) 
It has been resolved by writing my own Provider.
