### ISSUE TITLE
Add relation to same instance in differebt entities

### ISSUE THREAD

**Issue by bogdan-dubyk** [nelmio/alice#859]
Hi there, 

I have such  entities structure:
User has many Campaigns
User has many Creatives
Campaign has many Creatives

And  .yml file:
```
Project\Entities\User:
  user{1..5}:
    email (unique): '<email()>'
    firstName: '<firstName()>'
    lastName: '<lastName()>'
    password: '<bcrypt("q1w2e3r4")>'

Project\Entities\Campaign:
  campaign{1..100}:
    user: '@user*'
    name: '<company()>'

Project\Entities\Creative:
  creative{1..1000}:
    name: '<word()>'
    campaign: '@campaign*'
    user: '@user*' //i<---------issue is here
```
So  issue is in Creative part, I want to set user value same as we use in a related campaign (@campaign*), but not sure how to do that.

I tried:
```
Project\Entities\Creative:
  creative{1..1000}:
    name: '<word()>'
    campaign: '@campaign*'
    user: '$campaign->user'
```

but got the error   **Could not lex the value ">user"** , also I tried

```
Project\Entities\Creative:
  creative{1..1000}:
    name: '<word()>'
    campaign: '@campaign*'
    user: '@self->campaign->user'
```

and got the error   **Could not parse the token "@self->campaign->user" (type: PROPERTY_REFERENCE_TYPE).** 

Any ideas how to solve it?

**Comment by theofidry** [comment]
There is bound to be some expressions not working properly with the current Expression Language due to technical limitations of the current implementation. But `user: '$campaign->user'` is a relatively simple case so it should definitely work and if it's not it's a critical bug

**Comment by theofidry** [comment]
Sorry for the late reply.

It is weird that you are receiving a duplicate error for the users, did you purge your database properly in-between?

**Comment by bogdan-dubyk** [comment]
Yes, I'm refreshing all database migrations at the beginning of the command.
I made a very very dirty workaround to fix it, I'm looping through objects in order Users->Campaigns->Creatives, removing and replacing some relations.

```
   $loadedFile = $loader->loadFile($file);
   $objects = $loadedFile->getObjects();
   $loadedFile = null;
   $users = [];
   $campaigns= [];
   foreach ($objects as $name => $object) {
       if ($object instanceof User) {
           $em->persist($object);
           $users[$object->getEmail()] = $object;
           continue;
       } elseif ($object instanceof Campaign) {
           foreach ($object->getCreatives() as $creative) {
               $object->removeCreative($creative);
           }
           $em->persist($object);
           $campaigns[$object->getUser()->getEmail()] = $object;
            continue;
       } elseif ($object instanceof Creative) {
           $email = $object->getUser()->getEmail();
            if(isset($users[$email])) {
                $object->setUser($users[$email]);
            }
            if(isset($campaigns[$email])) {
                $object->setCampaign($campaigns[$email]);
            }
            $em->persist($object);
             continue;
       } else {
           $em->persist($object);
        }
   }
    $em->flush();
```

I know it's very weird but it's only way which works for me without any of duplication error :)

**Comment by theofidry** [comment]
>Looks like for some reason it considers each relation as a new entity and trying to insert instead of update record.

To me that's a big smell of a Doctrine misconfiguration/something weird in the entity classes. It often happens when the relations are not set properly or an entity is cloned somewhere.

You're workaround kinds of show it actually: you don't just do a persist but you need to re-set and remove values to make it work. If they are all created correctly then a persist on all + a flush should be enough. Now wether or not they are not created correctly comes from alice or your entites I can't tell. Your fixture files look alright at least and what is happening behind at the end of the day should be no more than calling the right mutators. An easy way to tell is to inspect the results of the loaded objects (e.g. by putting a break poin)

**Comment by ixarlie** [comment]
I'm facing with the same thing (Alice v3.2.0, Symfony 3, Doctrine ORM 2.6) and I think the issue here is the "deep_clone" function when using references (or variables) as arguments in fake providers. The entire argument array is "cloned", so every reference/variable is a **new instance** for Doctrine.

The debug trace is the following:
1. **FunctionCallValue**. As we are using a function call, Alice will create one with next content. (name = getUser, arguments = [FixtureReferenceValue|VariableValue, ...])
2. [**FunctionCallArgumentResolver**](https://github.com/nelmio/alice/blob/v3.2.0/src/Generator/Resolver/Value/Chainable/FunctionCallArgumentResolver.php#L94). Each argument is resolved with its argument resolver, then a [new FunctionCallValue is created](https://github.com/nelmio/alice/blob/v3.2.0/src/Definition/Value/FunctionCallValue.php#L40) (HERE WE LOSE KEEPING SAME INSTANCES) to be resolved again for the inner resolver.
3. **PhpFunctionCallValueResolver** -or- **FakerFunctionCallValueResolver** (depending if you use a native php function or a provider function)
4. Finally your provider is called returning a value.

The "deep_clone" line works well when the arguments are still ValueInterface, but introduces this behaviour in this scenario.

From the easiest to the most complicated workaround:
1. You could replace "deep_clone" function, with your own implementation, and add it a filter that skips your domain classes to be cloned. (because do some tricks in your domain like make private the __clone method is not affordable IMO)
2. You could decorate FunctionCallArgumentResolver to try avoid deep_clone in FunctionCallValue instantiation once your arguments are resolved.
3. You could extend Alice adding a new custom Flag somehow (requires to decorate SimpleValueDenormalizer in order to read your flags and return a proper ValueInterface for your resolver, simply crazy!)

@theofidry  any other suggestions?
Thanks!

**Comment by theofidry** [comment]
Another solution would be to create a ResolvedFunctionCall or something
were the arguments are not deep cloned
