### ISSUE TITLE
Question - Is possible to reference "static" data/entities

### ISSUE THREAD

**Issue by Eldhelion** [nelmio/alice#940]
So i'm trying to use this to generate fake data, but part of my database is static data (countries, states, cities) and I need that a generated entity, lets say "App\Entity\Address", I tried to put the id in the atribute, but received a error for trying to use integer where a Object is expected.

There is a way to do it? I saw nothing of the like in the doc

I know that I can manually create a subset in the fixture yml , but since I use this info,I would like variety / different combinations

**Comment by theofidry** [comment]
> I tried to put the id in the atribute, but received a error for trying to use integer where a Object is expected.

The reason why you didn't see any doc about it is because it's entirely up to your and your app. You need to imagine that behind it, it's plain PHP, so if you have a `setId(ObjectId $obj)` you will need to set an object not an int. One way to do those things would be to create a [custom faker provider](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers)

**Comment by Eldhelion** [comment]
hm, ok, seeing the custom fake provider, I think I now know what to do, thanks
